import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Hurmat Khalid</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" bg-teal-100 px-10">
				<section className="min-h-screen">
					<nav className="p-10 mb-12 flex justify-between">
						<h1 className=" text-xl font-burtons">Hurmat</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill className="cursor-pointer text-2xl" />
							</li>
							<li>
								<a
									className=" bg-gradient-to-r from-cyan-300 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
									href="#">
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div>
						<h2>Hurmat Khalid</h2>
						<h3>Developer and Film Maker</h3>
						<p>
							I'm a college sophomore doing my BTech in computer science and a
							diploma in Data Science. I am a front-end web developer. I like to
							build my projects from the ground up, from planning and designing
							all the way to solving real-life problems with code.
						</p>
					</div>
				</section>
			</main>
		</div>
	);
}
