import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillInstagram,
} from 'react-icons/ai';
import Image from 'next/image';
import hurmat from '../public/me.jpeg';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import { useState } from 'react';

export default function Home() {
	const [darkMode, setDarkmode] = useState(false);
	return (
		<div className={`${darkMode ? 'dark' : ''}`}>
			<Head>
				<title>Hurmat Khalid</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
				<section className="min-h-screen pb-8">
					<nav className="py-6 mb-12 flex justify-between dark:text-white">
						<h1 className=" text-xl font-burtons">Hurmat</h1>
						<ul className="flex items-center">
							<li>
								<BsFillMoonStarsFill
									onClick={() => setDarkmode(!darkMode)}
									className="cursor-pointer text-2xl"
								/>
							</li>
							<li>
								<a
									className=" bg-gradient-to-r from-cyan-300 to-teal-600 text-white px-4 py-2 rounded-md ml-8"
									href="#">
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-0">
						<h2 className="text-4xl p-2 text-teal-600 font-medium md:text-6xl">
							Hurmat Khalid
						</h2>
						<h3 className="text-2xl py-2 md:text-3xl dark:text-gray-500">
							Developer and Film Maker
						</h3>
						<p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-5xl mx-auto dark:text-white">
							I&apos;m a college sophomore doing my BTech in computer science
							and a diploma in Data Science. I am a front-end web developer. I
							like to build my projects from the ground up, from planning and
							designing all the way to solving real-life problems with code.
						</p>
					</div>
					<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
						<AiFillTwitterCircle />
						<AiFillLinkedin />
						<AiFillInstagram />
					</div>
					<div className="relative mx-auto my-8 rounded-full w-80 h-80 md:h-90 md:w-90">
						<Image
							src={hurmat}
							alt=""
							layout="fill"
							objectFit="cover"
							className="rounded-full"
						/>
					</div>
				</section>
				<section className="min-h-screen">
					<div>
						<h3 className="text-3xl py-1 text-center dark:text-gray-500">
							Services I offer
						</h3>
						<p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
							Lorem ipsum dolor sit amet consectetur adipisicing elit.
							Temporibus porro, veniam animi fugiat quas cum suscipit, maiores
							ea eveniet maxime delectus. Delectus officia nobis vel aliquam
							quisquam atque, quo nisi.
							<span className="text-teal-500">bold element</span> consulted for{' '}
							<span className="text-teal-500">another</span> Lorem ipsum dolor
							sit amet, consectetur adipisicing elit. Placeat accusantium
							expedita deserunt dolores repellendus!
						</p>
						<p className="dark:text-white">
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum quia,
							itaque perspiciatis corporis quam laborum dolorum dicta in
							provident
						</p>
					</div>
					<div className="lg:flex gap-10 dark:text-white">
						<div className=" flex flex-col justify-center items-center text-center shadow-lg p-10 rounded-xl my-10">
							<Image src={design} width={100} height={100} alt="" />
							<h3 className="text-lg font-medium pt-8 pb-2">Designing</h3>
							<p className="py-2">
								Creating elegant designs suited for your needs
							</p>
							<h4 className="py-2 text-teal-600">Tools:</h4>
							<p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
							<p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
						</div>
						<div className="flex flex-col justify-center items-center text-center shadow-lg p-10 rounded-xl my-10">
							<Image src={code} width={100} height={100} alt="" />
							<h3 className="text-lg font-medium pt-8 pb-2">Code</h3>
							<p className="py-2">
								Web Development and Competitive Programming
							</p>
							<h4 className="py-2 text-teal-600">Tools:</h4>
							<p className="text-gray-800 py-1 dark:text-gray-300">
								HTML, CSS, JavaScript, React, NextJS
							</p>
							<p className="text-gray-800 py-1 dark:text-gray-300">
								C++, C, Solidity,
							</p>
						</div>
						<div className="flex flex-col justify-center items-center text-center shadow-lg p-10 rounded-xl my-10">
							<Image src={consulting} width={100} height={100} alt="" />
							<h3 className="text-lg font-medium pt-8 pb-2">Mentor</h3>
							<p className="py-2">
								Active member of different clubs and communities
							</p>
						</div>
					</div>
				</section>
				<section className="py-10">
					<div>
						<h3 className="text-3xl py-1 text-center dark:text-gray-500">
							Portfolio
						</h3>
					</div>
					<p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
						he;;o what Lorem ipsum dolor sit amet consectetur adipisicing elit.
						Temporibus porro, veniam animi fugiat quas cum suscipit, maiores ea
						eveniet maxime delectus. Delectus officia nobis vel aliquam quisquam
						atque, quo nisi.
						<span className="text-teal-500">bold element</span> consulted for{' '}
						<span className="text-teal-500">another</span> Lorem ipsum dolor sit
						amet, consectetur adipisicing elit. Placeat accusantium expedita
						deserunt dolores repellendus!
					</p>
					<p className="dark:text-white">
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum quia,
						itaque perspiciatis corporis quam laborum dolorum dicta in provident
					</p>
				</section>
			</main>
		</div>
	);
}
